In [69]:
import spacy
import pandas as pd
from spacy.lang.en.stop_words import STOP_WORDS

In [70]:
data=pd.read_json("C:\\Users\\manju\\Downloads\\archive (30)\combined.json",lines=True)

In [71]:
nlp=spacy.load("en_core_web_sm")

In [72]:
def preprocess(doc):
    text=nlp(doc)
    not_space=[token.text for token in text if not token.is_stop and not token.is_punct]
    return " ".join(not_space)

In [73]:
doc=("I am learning NLP and I am using spaCy for text processing.")
preprocess(doc)

'learning NLP spaCy text processing'

In [74]:
data.head(10)

,id,title,contents,date,topics,components
0,NaN,Convicted Bomb Plotter Sentenced to 30 Years,"PORTLAND, Oregon. – Mohamed Osman Mohamud, 23,...",2014-10-01T00:00:00-04:00,[],[National Security Division (NSD)]
1,12-919,$1 Million in Restitution Payments Announced t...,WASHINGTON – North Carolina’s Waccamaw River...,2012-07-25T00:00:00-04:00,[],[Environment and Natural Resources Division]
2,11-1002,$1 Million Settlement Reached for Natural Reso...,BOSTON– A $1-million settlement has been...,2011-08-03T00:00:00-04:00,[],[Environment and Natural Resources Division]
3,10-015,10 Las Vegas Men Indicted \r\nfor Falsifying V...,WASHINGTON—A federal grand jury in Las Vegas...,2010-01-08T00:00:00-05:00,[],[Environment and Natural Resources Division]
4,18-898,$100 Million Settlement Will Speed Cleanup Wor...,"The U.S. Department of Justice, the U.S. Envir...",2018-07-09T00:00:00-04:00,[Environment],[Environment and Natural Resources Division]
5,NaN,105 Individuals Indicted for Violating the RIC...,A nine count federal indictment was unsealed t...,2015-07-22T00:00:00-04:00,[],[USAO - Puerto Rico]
6,14-032,12th Former Officer at Roxbury Correctional In...,"Michael Morgan, formerly an officer at Roxbury...",2014-01-10T00:00:00-05:00,[],"[Civil Rights Division, Civil Rights - Crimina..."
7,14-1412,14 Indicted in Connection with New England Com...,A 131-count criminal indictment was unsealed t...,2014-12-17T00:00:00-05:00,[Consumer Protection],[Civil Division]
8,14-849,14 Individuals Charged with Trafficking Identi...,Fourteen individuals were charged in three ...,2014-08-12T00:00:00-04:00,[],[Criminal Division]
9,15-089,"15th Member of Washington, D.C.-Based Identity...",Defendant Admits To Targeting Parents Of Hospi...,2015-01-23T00:00:00-05:00,[],[Criminal Division]

In [75]:
data.shape

(13087, 6)

In [76]:
data=data[data['topics'].str.len()!=0]

In [77]:
data.shape

(4688, 6)

In [78]:
data2=data.head(300)
data2["new_contents"]=data2['contents'].apply(preprocess)

In [79]:
data2.head(5)

,id,title,contents,date,topics,components,new_contents
4,18-898,$100 Million Settlement Will Speed Cleanup Wor...,"The U.S. Department of Justice, the U.S. Envir...",2018-07-09T00:00:00-04:00,[Environment],[Environment and Natural Resources Division],U.S. Department Justice U.S. Environmental Pro...
7,14-1412,14 Indicted in Connection with New England Com...,A 131-count criminal indictment was unsealed t...,2014-12-17T00:00:00-05:00,[Consumer Protection],[Civil Division],131 count criminal indictment unsealed today B...
19,17-1419,2017 Southeast Regional Animal Cruelty Prosecu...,The United States Attorney’s Office for the Mi...,2017-12-14T00:00:00-05:00,[Environment],"[Environment and Natural Resources Division, U...",United States Attorney Office Middle District ...
22,15-1562,21st Century Oncology to Pay $19.75 Million to...,"21st Century Oncology LLC, has agreed to pay $...",2015-12-18T00:00:00-05:00,"[False Claims Act, Health Care Fraud]",[Civil Division],21st Century Oncology LLC agreed pay $ 19.75 m...
23,17-1404,21st Century Oncology to Pay $26 Million to Se...,21st Century Oncology Inc. and certain of its ...,2017-12-12T00:00:00-05:00,"[Health Care Fraud, False Claims Act]","[Civil Division, USAO - Florida, Middle]",21st Century Oncology Inc. certain subsidiarie...

In [80]:
len(data2['new_contents'].iloc[4])

4217

In [81]:
len(data2['contents'].iloc[4])

5504